# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      PYTHONPATH: .
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      # Dash creates new step
      - name: Install Python dependencies
        run: | 
          pip install pytest
          pip install pytest-cov
          pip install openapi-python-client
          pip install -r BE/requirements.txt

      - name: Pip Install Playwright
        run: pip install playwright

      - name: Playwright   
        run: playwright install

      - name: Start Docker Compose containers
        run: |
          docker compose -p webcalculator up -d
          sleep 10
     

  # Run web tests
      - name: Run web tests
        run: |
          pytest -v --junit-xml=web-report.xml test/web/

      # Run unit tests
      - name: Run unit tests
        env:
          PYTHONPATH: ./test
        run: |
           pytest -v --junit-xml=report.xml test/test_api.py test/test_unit.py
          
      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v5      
        with:
          report_paths: '**/*.xml'
      
      - name: Upload Playwright traces
        if: always()                    # run even if tests failed
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: '**/*.zip'         # adjust if you use another folder
          if-no-files-found: ignore
          retention-days: 14

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build from BE folder
      - name: Build Docker image
        run: docker build -t judevops.azurecr.io/nicole_chiu-calculator ./BE
      - name: Push Docker image
        run: docker push judevops.azurecr.io/nicole_chiu-calculator
